first commit, help and service pages
Aloquei/aloquei_app pull request #50
Opened 2021-07-21 02:12 UTC by ThiagoSlvr

Primeira versão das páginas de help e serviços.

2021-07-21 02:13 UTC, ThiagoSlvr commented
Prints de como elas estão visualmente:

Help:
![help](https://user-images.githubusercontent.com/30842770/126419742-efc95d49-02e3-44ee-95a8-174a00c2627f.png)

Service:
![service](https://user-images.githubusercontent.com/30842770/126419749-4d137fae-23be-40dc-a657-2f548e243f47.png)

2021-07-21 13:08 UTC, matheusscheu requested changes
Eu percebi que o design de tela que tu esta utilizando é de quem não está logado no app, o que estamos utilizando é de quem está logado. O design da tela é um pouco diferente.

2021-07-22 14:41 UTC, matheusscheu requested changes

2021-07-22 14:41 UTC, matheusscheu commented on lib/screens/help/components/default_appbar.dart
> +          onPressed: onpressed2,
Como é um botão de voltar, ja pode colocar a função Navigator.pop(), não precisa criar um construtor

2021-07-22 14:41 UTC, matheusscheu commented on lib/screens/help/components/default_appbar.dart
> +        tabs: <Widget>[
retirar os <widget> do código

2021-07-22 14:41 UTC, matheusscheu commented on lib/screens/help/components/default_appbar.dart
> +        labelColor: Color(0xFF222222),
Todas as cores precisam estar na colors.dart

2021-07-22 14:41 UTC, matheusscheu commented on lib/screens/help/components/default_appbar.dart
> +          DefaultTab(
Identifica como Arquivos diferentes e não utiliza tanto a palavra default. Default é tudo aquilo que é default para o projeto, que será muito utilizado.

2021-07-22 14:41 UTC, matheusscheu commented on lib/screens/help/help_page.dart
> +                  child: ListView(children: [
Aqui como tu vai repetir o mesmo design tu pode usar o listview.tile

2021-07-22 14:41 UTC, matheusscheu commented on lib/screens/terms/terms_page.dart
> +      appBar: AppBarWithText(
Essa app bar eu tinha feito, ela sumiu.

2021-07-23 06:39 UTC, ThiagoSlvr commented
Todos Arquivos com default no Nome foram alterados
Todas as cores foram colocadas em colors.dart
1 onpressed virou o Navigator.pop
Os botões de artigos foram todos alterados para ListTiles

Em questão do appbar que tu tinha feito, não sei onde ela está, procurei na branch de develop e ela parece não estar lá também.

2021-07-23 20:49 UTC, matheusscheu approved these changes

2021-07-23 20:49 UTC, merged